version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3
        environment:
          PGHOST: localhost
          PGUSER: yays-or-nays-BE
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: yays-or-nays-BE
          POSTGRES_DB: yays-or-nays-BE_test
          POSTGRES_HOST_AUTH_METHOD: trust
    executor: ruby/default
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rails db:schema:load --trace
