# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

HotTake.destroy_all
Tag.destroy_all


food_tag = Tag.create(category: "Food & Beverage")
entertainment_tag = Tag.create(category: "Entertainment")
software_tag = Tag.create(category: "Software Development")
misc_tag = Tag.create(category: "Miscellaneous")


software_tag.hot_takes.create!(picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7PfyqeJD2TWb20o22uwCMrVCJVKDfi6AePD6uLCZZud_VMBBu&s", question: "Javascript is a good coding language", yes_vote: 1)
software_tag.hot_takes.create(picture: "https://www.zdnet.com/a/hub/i/r/2018/11/10/b17cc654-deac-44fe-b603-586d20602b5f/thumbnail/770x578/92e095da546979ad55d9aeb1c99c189a/ruby-programming-language.png", question: "Ruby is a great beginner coding language", yes_vote: 3)
software_tag.hot_takes.create(picture: "https://javapapers.com/wp-content/uploads/2011/01/DoubleBraceInitialization.jpg", question: "Javascript has too many unecessary brackets", yes_vote: 2)
software_tag.hot_takes.create(picture: "https://user-images.githubusercontent.com/11014462/32064927-988dfaba-ba7b-11e7-9c5b-4e945f2c6deb.png", question: "If you use VS Code and don't use the built in terminal it's weird", yes_vote: 1, no_vote: 1)
software_tag.hot_takes.create(picture: "https://raw.githubusercontent.com/akamud/vscode-theme-onelight/master/screenshots/preview.png", question: "Light mode on any application is terrible", yes_vote: 1, no_vote: 2)
software_tag.hot_takes.create(picture: "https://miro.medium.com/max/900/1*OrjCKmou1jT4It5so5gvOA.jpeg", question: "CSS does not belong in component files(lookin' at you, Vue)", yes_vote: 1, no_vote: 0)
software_tag.hot_takes.create(picture: "https://image.slidesharecdn.com/ad114-2012-120124214521-phpapp02/95/ad114-dont-be-afraid-of-curly-brackets-reloaded-even-more-javascript-for-lotusscript-developers-17-728.jpg?cb=1327442073", question: "JS has just the right amount of brackets", yes_vote: 1, no_vote: 0)
software_tag.hot_takes.create(picture: "https://media.geeksforgeeks.org/wp-content/uploads/20190813234845/tab-length1.png", question: "Four space tabs is a lot easier to read and it all gets compiled anyways", yes_vote: 1, no_vote: 0)
software_tag.hot_takes.create(picture: "https://www.morozov.is/assets/images/previews/partial_application.png", question: "Speed is a small and welcome price to pay for partials", yes_vote: 1, no_vote: 0)
software_tag.hot_takes.create(picture: "https://media.wired.com/photos/5d6998d04697d8000907f2ce/master/pass/notification-overload-83899390.jpg", question: "All threads and applications should default to notifications off", yes_vote: 1, no_vote: 0)
software_tag.hot_takes.create(picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVxoufrSx7Nfstrj5w5LjREmrsdtGo2flpTw&usqp=CAU", question: "CSS is just makeup for your website.", yes_vote: 1, no_vote: 0)
software_tag.hot_takes.create(picture: "https://play-lh.googleusercontent.com/OMqej9WONG1l8CXOgFH58XV1cGRgTcJxeffDiEXmkjkfLPK-g680lkzXGhJ7VMTmII4", question: "Opera Mini is the best browser", yes_vote: 1, no_vote: 0)

food_tag.hot_takes.create(picture: "1", question: "IPAs taste like bile", yes_vote: 1)
food_tag.hot_takes.create(picture: "1", question: "Boneless wings are better than bone-in wings", yes_vote: 2, no_vote: 3)
food_tag.hot_takes.create(picture: "1", question: "Whiteclaw does the job and shouldnt be downplayed", yes_vote: 1)
food_tag.hot_takes.create(picture: "1", question: "Connecticut is the pizza capital of the world", yes_vote: 2)
food_tag.hot_takes.create(picture: "1", question: "Angel Hair is the worst pasta", yes_vote: 1, no_vote: 2)
food_tag.hot_takes.create(picture: "1", question: "Dunkin Donuts > Krispy Kreme", yes_vote: 2, no_vote: 1)
food_tag.hot_takes.create(picture: "1", question: "Whataburger and In n Out are the same thing", yes_vote: 1, no_vote: 2)
food_tag.hot_takes.create(picture: "1", question: "Tomatoes are a drink", no_vote: 2)
food_tag.hot_takes.create(picture: "1", question: "Cinnamon is better in savory foods", yes_vote: 1)
food_tag.hot_takes.create(picture: "1", question: "Pizza is overrated", yes_vote: 1)
food_tag.hot_takes.create(picture: "1", question: "Soup is a drink.", yes_vote: 1, no_vote: 1)
food_tag.hot_takes.create(picture: "1", question: "If you have no eggs, ice cream is a great way to make french toast.", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "There's no law while drinkin' 'The Claw'", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "Water is technically lava. Think about it.", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "Screaming Sicilian is the best frozen pizza", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "Hot water is better than cold water", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "Room temperature water is the best water.", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "Nuts have no place in ice cream", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "Cheese or carrots don’t belong in/on cakes", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "Takis are better than Hot Cheetos", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "Boneless wings are just chicken nuggets", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "Sumo oranges are overrated", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "Wet food is generally better than dry food", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "Ketchup is a sauce, and thus a drink", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "In n Out is just FINE", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "Tea is just hot, brown water", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "Coffee is just hot, brown water", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "Poptarts are just breakfast ravioli", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "Pizza is a vegetable", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "Ozo coffee is garbage", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "Lukewarm food is gross. It’s gotta be piping hot or freezing cold or it’s trash", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "Coffee is juice", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "Whiteclaw does the job and shouldnt be downplayed", yes_vote: 1, no_vote: 0)
food_tag.hot_takes.create(picture: "1", question: "Hot pockets are better than most frozen pizza", yes_vote: 1, no_vote: 0)

entertainment_tag.hot_takes.create(picture: "1", question: "Most songs would be better without the flute", yes_vote: 1, no_vote: 2)
entertainment_tag.hot_takes.create(picture: "1", question: "The Queen's Gambit Needs More Chess", yes_vote: 1)
entertainment_tag.hot_takes.create(picture: "1", question: "The Chimera ant arc in HxH is not only the best arc of the series, but possibly the best of any anime/manga ever, period.", yes_vote: 1, no_vote: 2)
entertainment_tag.hot_takes.create(picture: "1", question: "The Empire did nothing wrong.", yes_vote: 1, no_vote: 1)
entertainment_tag.hot_takes.create(picture: "1", question: "Nicolas Cage is a good actor", yes_vote: 1)
entertainment_tag.hot_takes.create(picture: "1", question: "Tom Cruise sucks at acting", yes_vote: 1)
entertainment_tag.hot_takes.create(picture: "https://images-na.ssl-images-amazon.com/images/I/61d6m8%2BIjTL._AC_SX425_.jpg", question: "Marvel movies haven't been good since Iron Man 1", yes_vote: 1)
entertainment_tag.hot_takes.create(picture: "https://i.pinimg.com/736x/cd/41/03/cd41030830a2c9f37b52784342f6a722.jpg", question: "Mark Ruffalo is the hottest avenger", yes_vote: 1)
entertainment_tag.hot_takes.create(picture: "http://texasbusiness.org/wp-content/uploads/2020/03/mark_cuban.jpg", question: "When people say Mark Ruffalo I always picture Mark Cuban", yes_vote: 1)
entertainment_tag.hot_takes.create(picture: "https://i1.sndcdn.com/artworks-XhyjO8NEQ2SEzW8W-A2deHw-t500x500.jpg", question: "Tik Tok has taught me more than all previous schooling combined", yes_vote: 1)
entertainment_tag.hot_takes.create(picture: "https://www.normans.co.uk/blog/wp-content/uploads/2020/08/learn-flute.jpg", question: "Most songs would be better without the flute", yes_vote: 1)
entertainment_tag.hot_takes.create(picture: "https://encyclopediahysterica.files.wordpress.com/2013/10/krusty_stand_up_526185.png", question: "Clowns > standup clowns", yes_vote: 1)
entertainment_tag.hot_takes.create(picture: "https://static.tvtropes.org/pmwiki/pub/images/avatar_poster_4.png", question: "Avatar the Last Airbender isn’t an anime.", yes_vote: 1)
entertainment_tag.hot_takes.create(picture: "https://i.ytimg.com/vi/jo505ZyaCbA/maxresdefault.jpg", question: "The Beatles don’t hold up", yes_vote: 1)
entertainment_tag.hot_takes.create(picture: "https://insidepulse.com/wp-content/uploads/2011/04/Marvel-Universe-Logo-500.jpg", question: "The Marvel Universe is boring", yes_vote: 1)
entertainment_tag.hot_takes.create(picture: "https://townsquare.media/site/366/files/2013/12/Megadeth-vs-Metallica-CCM.jpg?w=980&q=75", question: "Megadeth is better than Metallica", yes_vote: 1)
entertainment_tag.hot_takes.create(picture: "https://i.pinimg.com/originals/a0/34/bd/a034bd9d166db8a170a38553be15b19c.jpg", question: "Pinky is the biggest brain", yes_vote: 1)

misc_tag.hot_takes.create(picture: "https://psmag.com/.image/t_share/MTMzNDQ4NzA2ODU3OTMzMjc4/shutterstock_286491776jpg.jpg", question: "Listening to music with someone else is one of the most intimate things one can do", yes_vote: 1)
misc_tag.hot_takes.create(picture: "https://cdn.styleblueprint.com/wp-content/uploads/2015/10/101043074.jpg", question: "Vests are torso shorts", yes_vote: 1)
misc_tag.hot_takes.create(picture: "http://www.barkbusters.co.uk/images/articles/7a4120f095480e9f2a2ad2a165d90313.jpg", question: "Animals don't get jokes", yes_vote: 1)
misc_tag.hot_takes.create(picture: "http://www.barkbusters.co.uk/images/articles/7a4120f095480e9f2a2ad2a165d90313.jpg", question: "Animals don't understand what you're saying", yes_vote: 1)
misc_tag.hot_takes.create(picture: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/United_States_Declaration_of_Independence.jpg/1200px-United_States_Declaration_of_Independence.jpg", question: "Diarrhea is cursive poop", yes_vote: 1)
misc_tag.hot_takes.create(picture: "https://bg6fhgmkni-flywheel.netdna-ssl.com/wp-content/uploads/2017/05/grilled-balsamic-carrot-dog-01@2x-683x1024.jpg", question: "Carrots are the best doggy-treat", yes_vote: 1)
misc_tag.hot_takes.create(picture: "https://i.pinimg.com/originals/34/e7/05/34e705e9190a6d89cd99917721738f80.jpg", question: "Candles are how we keep fire as pets", yes_vote: 1)
misc_tag.hot_takes.create(picture: "https://nolenlee.com/wp-content/uploads/2018/02/ThePandaIsFat_v06_Spread_Ambition.jpg", question: "Poems are just incomplete songs", yes_vote: 1)
misc_tag.hot_takes.create(picture: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRs8R5UYuyw88-6uSGmD5jCUv3ucK2Z1kukx4E3h6KfyXQ_WYmPAVjxMTfdXS7IO58Qha6YVmOwEEFY8HjuMd7jZHO9DcDGdiA1u09NPphxCmQBhPOEclC1Yg&usqp=CAE", question: "Socks are basically weak shoes", yes_vote: 1)
misc_tag.hot_takes.create(picture: "https://thumbs.dreamstime.com/z/tooth-brush-under-shower-22182540.jpg", question: "Brushing your teeth while showering is the FARTHEST thing from being efficient.", yes_vote: 1)
misc_tag.hot_takes.create(picture: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/United_States_Declaration_of_Independence.jpg/1200px-United_States_Declaration_of_Independence.jpg", question: "Cursive is actually super cool and should not be hard to read, unless the cursiver has bad cursive handwriting.", yes_vote: 1)
